/**
 * Mapa Nome do time -> ISO-2 para renderizar bandeiras via SVG
 * (country-flag-icons). Funciona igual em qualquer SO porque é vetor,
 * não depende da fonte de emojis do sistema.
 */
export const TEAM_ISO: Record<string, string> = {
  México: "MX",
  "África do Sul": "ZA",
  "Coreia do Sul": "KR",
  "República Tcheca": "CZ",
  Canadá: "CA",
  "Bósnia-Herzegovina": "BA",
  Qatar: "QA",
  Suíça: "CH",
  Brasil: "BR",
  Marrocos: "MA",
  Haiti: "HT",
  Escócia: "GB",
  "Estados Unidos": "US",
  Paraguai: "PY",
  Austrália: "AU",
  Turquia: "TR",
  Alemanha: "DE",
  Curaçao: "CW",
  "Costa do Marfim": "CI",
  Equador: "EC",
  Holanda: "NL",
  Japão: "JP",
  Suécia: "SE",
  Tunísia: "TN",
  Bélgica: "BE",
  Egito: "EG",
  Irã: "IR",
  "Nova Zelândia": "NZ",
  Espanha: "ES",
  "Cabo Verde": "CV",
  "Arábia Saudita": "SA",
  Uruguai: "UY",
  França: "FR",
  Senegal: "SN",
  Iraque: "IQ",
  Noruega: "NO",
  Argentina: "AR",
  Argélia: "DZ",
  Áustria: "AT",
  Jordânia: "JO",
  Portugal: "PT",
  "RD do Congo": "CD",
  Uzbequistão: "UZ",
  Colômbia: "CO",
  Inglaterra: "GB",
  Croácia: "HR",
  Gana: "GH",
  Panamá: "PA",
};

export function isoForTeam(team: string): string | null {
  return TEAM_ISO[team] ?? null;
}
