import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

function git(cmd) {
  try {
    return execSync(cmd, { encoding: "utf-8" }).trim();
  } catch {
    return "dev";
  }
}

const count = git("git rev-list --count HEAD");
const hash = git("git rev-parse --short HEAD");

const content = `// Auto-generated by scripts/version.mjs
export const APP_VERSION = "${count}";
export const APP_COMMIT = "${hash}";
`;

writeFileSync(join(__dirname, "..", "src", "lib", "version.ts"), content);
console.log(`Version generated: v${count}.${hash}`);
