/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRankingRouteImport } from './routes/_app.ranking'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPalpitesRouteImport } from './routes/_app.palpites'
import { Route as AppGestaoRouteImport } from './routes/_app.gestao'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminResultadosRouteImport } from './routes/_app.admin.resultados'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPalpitesRoute = AppPalpitesRouteImport.update({
  id: '/palpites',
  path: '/palpites',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRoute = AppGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminResultadosRoute = AppAdminResultadosRouteImport.update({
  id: '/admin/resultados',
  path: '/admin/resultados',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/gestao': typeof AppGestaoRoute
  '/palpites': typeof AppPalpitesRoute
  '/perfil': typeof AppPerfilRoute
  '/ranking': typeof AppRankingRoute
  '/admin/resultados': typeof AppAdminResultadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/gestao': typeof AppGestaoRoute
  '/palpites': typeof AppPalpitesRoute
  '/perfil': typeof AppPerfilRoute
  '/ranking': typeof AppRankingRoute
  '/admin/resultados': typeof AppAdminResultadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gestao': typeof AppGestaoRoute
  '/_app/palpites': typeof AppPalpitesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/admin/resultados': typeof AppAdminResultadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/gestao'
    | '/palpites'
    | '/perfil'
    | '/ranking'
    | '/admin/resultados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/gestao'
    | '/palpites'
    | '/perfil'
    | '/ranking'
    | '/admin/resultados'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/gestao'
    | '/_app/palpites'
    | '/_app/perfil'
    | '/_app/ranking'
    | '/_app/admin/resultados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/palpites': {
      id: '/_app/palpites'
      path: '/palpites'
      fullPath: '/palpites'
      preLoaderRoute: typeof AppPalpitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestao': {
      id: '/_app/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AppGestaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/resultados': {
      id: '/_app/admin/resultados'
      path: '/admin/resultados'
      fullPath: '/admin/resultados'
      preLoaderRoute: typeof AppAdminResultadosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGestaoRoute: typeof AppGestaoRoute
  AppPalpitesRoute: typeof AppPalpitesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingRoute: typeof AppRankingRoute
  AppAdminResultadosRoute: typeof AppAdminResultadosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGestaoRoute: AppGestaoRoute,
  AppPalpitesRoute: AppPalpitesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingRoute: AppRankingRoute,
  AppAdminResultadosRoute: AppAdminResultadosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
